# -*- mode: poly-org -*-
* Keybindings
** Switch keys for better Dvorak compatibility
#+BEGIN_SRC emacs-lisp
(define-key key-translation-map [?\C-h] [?\C-x]) ;x for eXplain
(define-key key-translation-map [?\C-x] [?\C-h]) ;h for hang on, I have more input
(define-key key-translation-map [?\C-t] [?\C-f]) ;f for Flip two letters
(define-key key-translation-map [?\C-f] [?\C-t]) ;t for Toward the end of the line/file
(define-key key-translation-map (kbd "C-M-h") (kbd "C-M-x"))
(define-key key-translation-map (kbd "C-M-f") (kbd "C-M-t"))
(define-key key-translation-map (kbd "C-M-t") (kbd "C-M-f"))
(define-key key-translation-map (kbd "C-M-S-f") (kbd "C-M-S-t"))
(define-key key-translation-map (kbd "C-M-S-t") (kbd "C-M-S-f"))
(define-key key-translation-map (kbd "M-t") (kbd "M-f"))
(define-key key-translation-map (kbd "M-f") (kbd "M-t"))
(define-key key-translation-map (kbd "M-F") (kbd "M-T"))
(define-key key-translation-map (kbd "M-T") (kbd "M-F"))
#+END_SRC

** Global key bindings
#+BEGIN_SRC emacs-lisp
(add-hook 'org-mode-hook
          (lambda () (local-set-key (kbd "C-,")
                                    (lambda () (interactive)
                                      (other-window -1)))))

(global-set-key (kbd "<f5>") (lambda () (interactive) (revert-buffer nil t)))
(global-set-key (kbd "M-p") 'backward-paragraph)
(global-set-key (kbd "M-n") 'forward-paragraph)

(global-set-key (kbd "M-,")
                (lambda () (interactive) (other-window -1)))
(global-set-key (kbd "M-.") 'other-window)
(global-set-key (kbd "C-,")
                (lambda () (interactive) (other-window -1)))
(global-set-key (kbd "C-.") 'other-window)

(global-set-key (kbd "C-z") 'zap-to-char)
(global-set-key (kbd "C-x p") 'pop-to-mark-command)
(global-set-key (kbd "C-x b") 'helm-bookmarks)
(global-set-key (kbd "C-x w") 'eww)
(global-set-key (kbd "M-r") 'query-replace-regexp)
(global-set-key (kbd "C-M-r") 'query-replace-regexp)
(global-set-key (kbd "C-M-d") 'kill-sexp)
(global-set-key (kbd "C-h o") 'man)
#+END_SRC

Swap =undo= and =universal-argument=. =C-u= is in too good of a position to be wasted on =universal-argument=.
#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "C-u") 'undo)
(global-set-key (kbd "C-/") 'universal-argument)
#+END_SRC

** Keybindings for external packages
#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "C-x m") 'mu4e)
(global-set-key (kbd "C-s") 'swiper)
(global-set-key (kbd "C-x g") 'magit-status)
(global-set-key (kbd "C-r") 'ace-window)
(global-set-key (kbd "M-m") 'er/expand-region)
(global-set-key (kbd "C-x f") 'anchored-transpose)
(global-set-key (kbd "C-M-s") 'helm-do-ag)
(global-set-key (kbd "C-;") 'whole-line-or-region-comment-dwim)
#+END_SRC

*** avy
#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "M-s") 'avy-goto-subword-1)
(global-set-key (kbd "M-g M-g") 'avy-goto-line)
(global-set-key (kbd "M-g g") 'avy-goto-line)
#+END_SRC

*** deft
#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "C-x d") 'deft)
#+END_SRC

*** flycheck
#+BEGIN_SRC emacs-lisp
(add-hook 'flycheck-mode-hook
          (lambda ()
            (local-set-key (kbd "C-M-n") #'flycheck-next-error)
            (local-set-key (kbd "C-M-p") #'flycheck-previous-error)))
#+END_SRC

*** helm
#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "M-x") 'helm-M-x)
(global-set-key (kbd "M-y") 'helm-show-kill-ring)
(global-set-key (kbd "C-x C-f") 'helm-find-files)
(global-set-key (kbd "C-x C-b") 'helm-mini)
(global-set-key (kbd "C-x C-n") 'helm-mini)
(global-set-key (kbd "C-h a") 'helm-apropos)
(global-set-key (kbd "C-h x") 'helm-google-suggest)
(global-set-key (kbd "C-l") 'helm-locate)
#+END_SRC

*** corral
#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "M-9") 'corral-parentheses-backward)
(global-set-key (kbd "M-0") 'corral-parentheses-forward)
(global-set-key (kbd "M-[") 'corral-brackets-backward)
(global-set-key (kbd "M-]") 'corral-brackets-forward)
(global-set-key (kbd "M-{") 'corral-braces-backward)
(global-set-key (kbd "M-}") 'corral-braces-forward)
(global-set-key (kbd "M-\"") 'corral-double-quotes-backward)
(global-set-key (kbd "M-'") 'corral-single-quotes-backward)
#+END_SRC

** Keybindings for custom defined functions
#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "<C-return>") 'open-next-line)
(global-set-key (kbd "M-RET") 'open-next-line)
(global-set-key (kbd "C-o") 'open-next-line) ;like vi o
(global-set-key (kbd "C-x C-r") 'find-file-sudo)
(global-set-key (kbd "M-o") 'open-previous-line) ;like vi O
(global-set-key (kbd "<f8>") 'run-async-script)
(global-set-key (kbd "C-a") 'beginning-of-line-or-indentation)
#+END_SRC

* General Settings
** Package Management
Use melpa as package repository.
#+BEGIN_SRC emacs-lisp
(require 'package)
(add-to-list 'package-archives
             '("melpa" . "https://melpa.org/packages/"))
(add-to-list 'package-archives
             '("melpa-stable" . "https://stable.melpa.org/packages/"))
(add-to-list 'package-archives '("org" . "http://orgmode.org/elpa/") t)
#+END_SRC

Load and activate packages.
#+BEGIN_SRC emacs-lisp
(package-initialize)
#+END_SRC

Check if package-initialize did anything.  If nil, this is probably the first time starting emacs, so contact the package archives to refresh the package list.
#+BEGIN_SRC emacs-lisp
(unless package-activated-list (package-refresh-contents))
#+END_SRC

Regenerate any missing packages.
#+BEGIN_SRC emacs-lisp
(setq my-packages '(@ queue ace-window avy afternoon-theme aggressive-indent anchored-transpose atom-one-dark-theme auctex auto-complete popup avy beacon seq bubbleberry-theme cider seq spinner queue pkg-info epl clojure-mode clojure-mode color-theme-sanityinc-tomorrow column-enforce-mode s dash f pythonic company company-irony irony company company-irony-c-headers corral cyberpunk-theme darktooth-theme deft draft-mode epc ctable concurrent deferred erc-hl-nicks expand-region find-file-in-project swiper firecode-theme flycheck-irony irony flycheck seq let-alist pkg-info epl dash flycheck-package flycheck seq let-alist pkg-info epl dash focus gnugo xpm ascii-art-to-unicode grandshell-theme haskell-mode helm-ag helm helm-core async popup async helm-projectile dash projectile pkg-info epl dash helm helm-core async popup async highlight-indentation htmlize hungry-delete irony jinja2-mode js2-mode json-rpc kerl let-alist load-theme-buffer-local lush-theme magit magit-popup dash async git-commit with-editor dash async dash with-editor dash async dash async magit-popup dash async material-theme minesweeper monokai-theme multi multiple-cursors names noctilux-theme paredit popup projectile pkg-info epl dash puml-mode py-autopep8 python-environment deferred pythonic pyvenv queue rainbow-delimiters request seq simple-httpd rich-minority smyx-theme solarized-theme dash soothe-theme spacegray-theme spinner sr-speedbar string-utils list-utils stripe-buffer swiper symon temp-buffer-browse tronesque-theme ujelly-theme diminish bind-key web-mode whole-line-or-region with-editor dash async writegood-mode ws-butler xpm yaml-mode yasnippet zenburn-theme))

(mapc (lambda (package)
        (unless (package-installed-p package)
          (package-install package)))
      my-packages)
#+END_SRC

Pin packages to melpa-stable, since melpa versions will always have a higher version number.
#+BEGIN_SRC emacs-lisp
(add-to-list 'package-pinned-packages '("cider" . "melpa-stable"))
#+END_SRC

** Appearance
*** Cursor
#+BEGIN_SRC emacs-lisp
;;(set-cursor-color "white")
(blink-cursor-mode 0)
#+END_SRC

*** Font
#+BEGIN_SRC emacs-lisp
(add-to-list 'default-frame-alist '(font . "Ubuntu Mono-15"))
#+END_SRC

*** Frame title
#+BEGIN_SRC emacs-lisp
(setq phrases `("conlidimus nostra ultra pensum"))
#+END_SRC

#+BEGIN_SRC emacs-lisp
(add-hook 'after-init-hook
          (lambda () (setq frame-title-format 'mode-line-format)))
#+END_SRC

*** Toolbars
#+BEGIN_SRC emacs-lisp
(menu-bar-mode 0)
(tool-bar-mode 0)
#+END_SRC

*** Mode line
Show column number in mode line.
#+BEGIN_SRC emacs-lisp
(column-number-mode 1)
#+END_SRC

*** Theme
#+BEGIN_SRC emacs-lisp
(setq favorite-themes
      '(grandshell tronesque cyberpunk afternoon sanityinc-tomorrow-bright
                   deeper-blue material sanityinc-tomorrow-blue soothe noctilux))

(setq theme-combos
      '((load-theme 'solarized-dark t)
        (load-theme 'jazz t)))

(setq solarized-scale-org-headlines nil)
(load-theme 'solarized-dark t)
(load-theme 'jazz t)

#+END_SRC

**** Optional settings
#+BEGIN_SRC emacs-lisp
                                        ;(set-face-background 'default "#000000")
                                        ;(set-face-foreground 'default "#BCBCBC")
#+END_SRC
     
*** Fringes
#+BEGIN_SRC emacs-lisp
(fringe-mode '(4 . 0))
(scroll-bar-mode 0)
#+END_SRC

** Editor behavior
*** Autosave
Set autosave directory so that all the autosaves are in one place, and not all over the filesystem.
#+BEGIN_SRC emacs-lisp
(setq backup-directory-alist `(("." . "/home/nivekuil/.emacs.d/backup")))
(setq auto-save-list-file-prefix "/home/nivekuil/.emacs.d/autosave/")
(setq auto-save-file-name-transforms
      `((".*" , "/home/nivekuil/.emacs.d/autosave/" t)))
#+END_SRC

Disable autosave based on number of characters typed.  Autosave after 10 seconds of idle.
#+BEGIN_SRC emacs-lisp
(setq auto-save-interval 0)
(setq auto-save-timeout 10)
#+END_SRC

*** Dired
When multiple dired buffers are open, dired should assume that file operations should be directed to the path in the other dired buffer.
#+BEGIN_SRC emacs-lisp
(setq dired-dwim-target nil)
#+END_SRC

*** Eldoc
This should be lower than flycheck-display-errors-delay so it doesn't clobber it.
#+BEGIN_SRC emacs-lisp
(setq eldoc-idle-delay 0.3)
#+END_SRC
*** Fill column
fill commands should create rows up to to 78 characters long.
#+BEGIN_SRC emacs-lisp
(setq-default fill-column 78)
#+END_SRC

*** Scrolling
Make scrolling behave smoothly.  Note that scrolling does not work correctly with hl-line-mode after cursor goes to the bottom of the buffer.
#+BEGIN_SRC emacs-lisp
(setq scroll-margin 7
      scroll-conservatively 10000)
#+END_SRC

Change how many lines mouse wheel scrolls by - 1 line at a time with no modifiers.
#+BEGIN_SRC emacs-lisp
(setq mouse-wheel-scroll-amount '(1 ((shift) . 3) ((control) . 8)))
#+END_SRC

*** Yanking (pasting)
If we copy something from outside emacs, save it in the kill ring so it doesn't get lost after a kill.
#+BEGIN_SRC emacs-lisp
(setq save-interprogram-paste-before-kill t)
#+END_SRC

*** Increase garbage collection memory threshold
By default Emacs GC'd every .76MB allocated, which is far too aggressive for a modern machine.  Raise this to a much bigger number.
#+BEGIN_SRC emacs-lisp
(setq gc-cons-threshold 20000000)
#+END_SRC

*** Increase undo limit
#+BEGIN_SRC emacs-lisp
(setq undo-limit 800000)
(setq undo-strong-limit 1200000)
#+END_SRC

*** Spell checking
Disable these keybindings for flyspell.
#+BEGIN_SRC emacs-lisp
(eval-after-load "flyspell"
  (lambda ()
    (define-key flyspell-mode-map (kbd "C-.") nil)
    (define-key flyspell-mode-map (kbd "C-,") nil)))
(setq ispell-program-name "/usr/bin/hunspell")
#+END_SRC
** Web browsing
Shadow the original browse-url function, making it work appropriate to the frame's environment (graphical or terminal).
#+BEGIN_SRC emacs-lisp
(setq browse-url-generic-program (executable-find "google-chrome-stable"))
(add-hook 'after-init-hook (lambda ()
                             (defun browse-url (url &rest _)
                               "Shadow the original `browse-url' function, making it work appropriate to the frame's environment (graphical or terminal) by using either xdg-open or eww."
                               (interactive)
                               (if (display-graphic-p)
                                   (browse-url-generic url)
                                 (eww-browse-url url)))))
#+END_SRC

** Message buffer
Timestamp each message.
#+BEGIN_SRC emacs-lisp
(defadvice message (before when-was-that activate)
  "Add timestamps to `message' output."
  (when-let (message (ad-get-arg 0))
    (ad-set-arg 0 (concat (format-time-string "[%T] ") message))))
#+END_SRC

** Shell
Don't pop up the async shell command buffer.
#+BEGIN_SRC emacs-lisp
(add-to-list 'display-buffer-alist (cons "\\*Async Shell Command\\*.*" (cons #'display-buffer-no-window nil)))
#+END_SRC
** TRAMP
Don't litter directories with history files.
#+BEGIN_EXAMPLE
(setq tramp-histfile-override "/tmp/.tramp_history")
#+END_EXAMPLE

* Custom Functions
** Commands
*** Run current buffer in interpreter asynchronously
#+BEGIN_SRC emacs-lisp
(defun run-async-script ()
  (interactive)
  (save-buffer)
  (cond ((equal (file-name-extension buffer-file-name) "py")
         (async-shell-command (concat "python " buffer-file-name)))))
#+END_SRC

*** find-file-sudo
#+BEGIN_SRC emacs-lisp
(defun find-file-sudo ()
  "Reopen the current file as root, preserving point position."
  (interactive)
  (let ((p (point)))
    (find-alternate-file (concat "/sudo:root@localhost:" buffer-file-name))
    (goto-char p)))
#+END_SRC

*** open-next-line
Behave like vi's o command
Binding: C-o, C-RET, M-RET
#+BEGIN_SRC emacs-lisp
(defun open-next-line ()
  "Open a new line after the current one."
  (interactive)
  (end-of-line) (open-line 1) (forward-line) (indent-according-to-mode))
#+END_SRC

*** open-previous-line
Behave like vi's O command
Binding: M-o
#+BEGIN_SRC emacs-lisp
(defun open-previous-line ()
  "Open a new line before the current one."
  (interactive)
  (beginning-of-line) (open-line 1) (indent-according-to-mode))
#+END_SRC

*** mark-this-line
Binding: M-m
#+BEGIN_SRC emacs-lisp
(defun mark-this-line ()
  "Mark the current line from indentation to end, leaving cursor at end."
  (interactive)
  (back-to-indentation) (set-mark-command nil) (end-of-line))
#+END_SRC

*** correct-exponent-formatting-in-region
#+BEGIN_SRC emacs-lisp
(defun correct-exponent-formatting-in-region (start end)
  "Corrects formatting of exponents from copied text.
When yanking formatted text, the formatting of exponents will be lost,
appearing as regular numbers instead.  This function adds carets to properly
denote that they are exponents, including exponents of parenthetical
expressions.  This function assumes that the input variable is never an
exponent itself."
  (interactive "*r")
  (save-excursion
    (save-restriction
      (let ((character (read-string "Enter variable to add carets around: ")))
        (narrow-to-region start end)
        (goto-char (point-min))
        (while (re-search-forward (concat "[" character ")]") nil t)
          (when (looking-at-p "[[:digit:]]") (insert "^")))))))
#+END_SRC

*** beginning-of-line-or-indentation
Cycle cursor between the beginning of indentation and beginning of the line.

#+BEGIN_SRC emacs-lisp
(defun beginning-of-line-or-indentation ()
  (interactive)
  (let ((original (point)))
    (back-to-indentation)
    (if (eq (point) original)
        (beginning-of-line))))
#+END_SRC

*** spit-scad-last-expression
Using a clojure nrepl, scad-clj can interactively update a file to be read by an OpenSCAD session.
#+BEGIN_SRC emacs-lisp
(defun spit-scad-last-expression ()
  (interactive)
  (cider-interactive-eval
   (format
    "(require 'scad-clj.scad)
(spit \"repl.scad\" (scad-clj.scad/write-scad %s))"
   (cider-defun-at-point))))

(add-hook 'clojure-mode-hook
          (lambda ()
            (local-set-key (kbd "C-c c") 'spit-scad-last-expression)))
#+END_SRC

*** set-frame-width-80col
Make the current window 80 columns wide.
#+BEGIN_SRC emacs-lisp
(defun set-frame-width-80col (&optional cols)
  (interactive "p")
  (set-frame-width (selected-frame) (+ (* 81 cols) (- cols 1)))
  (set-frame-height (selected-frame) (x-display-pixel-height))
  (if (> cols 0)
      (set-frame-position (selected-frame) 0 0)
    (set-frame-position (selected-frame) -1 0)))
#+END_SRC

*** irc
#+BEGIN_SRC emacs-lisp
(defun connect-to-irc ()
  (interactive)
  ;; (erc-tls :server "irc.freenode.net" :port 6697
  ;;          :nick "nivekuil"
  ;;          :password (with-temp-buffer
  ;;                      (insert-file-contents (concat user-emacs-directory "ercpass"))
  ;;                      (buffer-string)))
  (erc-tls :server "nivekuil.com" :port 7000
           :nick "nivekuil"
           :password (with-temp-buffer
                       (insert-file-contents
                         (concat user-emacs-directory "ercpass.gpg"))
                       (buffer-string))))
#+END_SRC

*** jump-to-last-edit
#+BEGIN_SRC emacs-lisp
(defun jump-to-last-edit ()
  "Go back to last add/delete edit"
  (interactive)
  (let* ((ubuf (cadr buffer-undo-list))
     (beg (car ubuf))
     (end (cdr ubuf)))
    (cond
     ((integerp beg) (goto-char beg))
     ((stringp beg) (goto-char (abs end))
      (message "DEL-> %s" (substring-no-properties beg)))
     (t (message "No add/delete edit occurred")))))

(global-set-key (kbd "C-x u") 'jump-to-last-edit)
#+END_SRC

*** compile-dwim
#+BEGIN_SRC emacs-lisp
(defun compile-dwim ()
  (interactive)
  (save-buffer)
  (save-window-excursion
    (recompile)))
#+END_SRC
* Mode settings
** Minor modes
Use subword mode in prog mode to move by camelCase.
#+BEGIN_SRC emacs-lisp
(add-hook 'prog-mode-hook 'subword-mode)
#+END_SRC

Use winner-mode to save window layout history (C-c left to undo window changes)
#+BEGIN_SRC emacs-lisp
(winner-mode t)
#+END_SRC

Use hl line mode in dired, one of the few modes where it's more helpful than annoying.
#+BEGIN_SRC emacs-lisp
(add-hook 'dired-mode-hook 'hl-line-mode)
#+END_SRC

Use electric pair mode to automatically insert matching delimiters (sometimes annoying).
#+BEGIN_SRC emacs-lisp
(electric-pair-mode t)
#+END_SRC

Use mouse avoidance mode so the rodent doesn't cover the actual cursor.  I don't even notice I have this mode enabled, which is a probably a positive sign.
#+BEGIN_SRC emacs-lisp
(mouse-avoidance-mode 'exile)
#+END_SRC

Tab inserts spaces only.
#+BEGIN_SRC emacs-lisp
(setq-default indent-tabs-mode nil)
#+END_SRC

Use auto-revert-mode for log files to update the output automatically
#+BEGIN_SRC emacs-lisp
(add-to-list 'auto-mode-alist '("\\.log\\'" . auto-revert-mode))
#+END_SRC

*** recentf-mode
A useful feature that stores the most recently visited files, conveiniently accessible via =helm-mini=.
#+BEGIN_SRC emacs-lisp
(recentf-mode)
(setq recentf-max-saved-items 50)
(setq recentf-auto-cleanup 30)
(add-hook 'kill-emacs-hook 'recentf-save-list)
(add-hook 'auto-save-hook 'recentf-save-list)
#+END_SRC

Ignore autoloaded files that clobber the recentf list after upgrading packages.
#+BEGIN_SRC emacs-lisp
(setq recentf-exclude (list "/\\.git/.*\\'" ; Git contents
                            "/elpa/.*\\'"   ; Package files
                            "/itsalltext/"  ; It's all text temp files
                            ".*\\.gz\\'"
                            "TAGS"
                            ".*-autoloads\\.el\\'"))
#+END_SRC

** Major modes
*** Assembly
Configuration for SPARC assembly. Use ! as the comment char and only use tabs.
#+BEGIN_SRC emacs-lisp
(setq asm-comment-char ?!)
(setq asm-mode-hook
      (lambda ()
        (setq indent-tabs-mode t)
        (add-hook 'before-save-hook
                  (lambda () (tabify (point-min) (point-max))) nil t)))
#+END_SRC

*** C/C++ (cpp)
Use irony-mode.
#+BEGIN_SRC emacs-lisp
(add-hook 'c++-mode-hook 'irony-mode)
(add-hook 'c-mode-hook 'irony-mode)
(add-hook 'objc-mode-hook 'irony-mode)

;; replace the `completion-at-point' and `complete-symbol' bindings in
;; irony-mode's buffers by irony-mode's function
(defun my-irony-mode-hook ()
  (define-key irony-mode-map [remap completion-at-point]
    'irony-completion-at-point-async)
  (define-key irony-mode-map [remap complete-symbol]
    'irony-completion-at-point-async))
(add-hook 'irony-mode-hook 'my-irony-mode-hook)
(add-hook 'irony-mode-hook 'irony-cdb-autosetup-compile-options)
(add-hook 'irony-mode-hook 'irony-eldoc)
(setq irony-additional-clang-options '("-std=c++14"))

(add-hook 'irony-mode-hook
          (lambda nil (local-set-key (kbd "C-c C-c") 'compile-dwim)))
#+END_SRC

*** Clojure
#+BEGIN_SRC emacs-lisp
(add-hook 'clojure-mode-hook 'paredit-mode)
(add-hook 'clojure-mode-hook
          (lambda ()
            (local-set-key
             (kbd "C-;")
             (lambda ()
               "Comment out the sexp at point."
               (interactive)
               (save-excursion
                 (mark-sexp)
                 (paredit-comment-dwim))))))
#+END_SRC

#+BEGIN_SRC emacs-lisp
(add-hook 'clojure-mode-hook
          (lambda ()
            (local-set-key (kbd "C-l") 'cider-eval-defun-at-point)))
#+END_SRC
*** Comint
There should be no scroll margin in a shell buffer.
#+BEGIN_SRC emacs-lisp
(add-hook 'comint-mode-hook (lambda ()
                              (set (make-local-variable 'scroll-margin) 0)))
(setq comint-prompt-read-only t)
#+END_SRC

*** Conf
Use tabs in Unix conf files.
#+BEGIN_SRC emacs-lisp
(add-hook 'conf-mode (lambda () (setq indent-tabs-mode t)))
#+END_SRC

*** Emacs lisp  (elisp)
#+BEGIN_SRC emacs-lisp
(add-hook 'emacs-lisp-mode-hook 'paredit-mode)
#+END_SRC

*** Eww
#+BEGIN_SRC emacs-lisp
(eval-after-load "eww"
  '(progn (define-key eww-mode-map "n" 'next-line)
          (define-key eww-mode-map "m" 'eww-follow-link)
          (define-key eww-mode-map "p" 'previous-line)
          (define-key eww-mode-map "N" 'eww-next-url)
          (define-key eww-mode-map "P" 'eww-previous-url)))
(setq shr-color-visible-luminance-min 70)
#+END_SRC

*** ERC
Autojoin channels when ERC starts.
#+BEGIN_SRC emacs-lisp
(setq erc-autojoin-channels-alist nil)
'(("freenode.net" "#ucsd"))
#+END_SRC

Add modules to be loaded.
#+BEGIN_SRC emacs-lisp
  (require 'erc)
(add-to-list 'erc-modules 'hl-nicks)
(add-to-list 'erc-modules 'notifications)
(add-to-list 'erc-modules 'spelling)
#+END_SRC

Hide those annoying join/quit messages.
#+BEGIN_SRC emacs-lisp
(setq erc-hide-list '("JOIN" "PART" "QUIT"))
#+END_SRC

No scroll margin in ERC buffers.
#+BEGIN_SRC emacs-lisp
(add-hook 'erc-mode-hook (lambda ()
                            (set (make-local-variable 'scroll-margin) 1)))
#+END_SRC

Since we're using ZNC, DETACH instead of PART from a channel when killing its buffer.
#+BEGIN_SRC emacs-lisp
(defun erc-detach ()
  (erc-server-send (format "DETACH %s" (erc-default-target))
                   nil (erc-default-target)))

(setq erc-kill-buffer-hook #'(erc-detach))
(setq erc-kill-channel-hook #'(erc-detach))
(setq erc-kill-server-hook #'(erc-detach))
#+END_SRC

*** Haskell
#+BEGIN_SRC emacs-lisp
(require 'haskell-interactive-mode)
(require 'haskell-process)
(add-hook 'haskell-mode-hook
          (progn
              (interactive-haskell-mode)
              (turn-on-haskell-indent)))

(setq haskell-process-suggest-remove-import-lines t)
(setq haskell-process-auto-import-loaded-modules t)
(setq haskell-process-log t)

#+END_SRC

*** Help
#+BEGIN_SRC emacs-lisp
(add-hook 'help-mode-hook 'visual-line-mode)
#+END_SRC
*** LaTeX
Use xelatex in org export.
#+BEGIN_SRC emacs-lisp
;; (setq org-latex-default-packages-alist
;;       (remove '("AUTO" "inputenc" t) org-latex-default-packages-alist))
;; (add-to-list 'org-latex-packages-alist '("" "xltxtra" t))
;; (setq org-export-dispatch-use-expert-ui nil) ; non-intrusive export dispatch
;; (setq org-latex-pdf-process               ; for regular export
;;       '("xelatex -shell-escape -interaction nonstopmode -output-directory %o
;; %f"
;;         "xelatex -shell-escape -interaction nonstopmode -output-directory %o
;; %f"
;;         "xelatex -shell-escape -interaction nonstopmode -output-directory %o
;; %f"))
;; (setq latex-run-command "xelatex")
#+END_SRC

Automatically compile on save.  There's probably a better way to do this that avoids the undocumented variable =TeX-command-force=.

#+BEGIN_SRC emacs-lisp
(setq TeX-command-force "LaTeX")
(add-hook 'LaTeX-mode-hook
          (lambda () (add-hook 'after-save-hook
                               (lambda () (TeX-command-master -1)) nil t)))
#+END_SRC
*** Python
#+BEGIN_SRC emacs-lisp
(when (executable-find "ipython")
      (setq python-shell-intrepreter "ipython"))
#+END_SRC
*** Org-mode
Use visual line mode to wrap lines in org mode.
#+BEGIN_SRC emacs-lisp
(add-hook 'org-mode-hook 'visual-line-mode)
#+END_SRC

Indent sections and hide multiple asterisks.
#+BEGIN_SRC emacs-lisp
(setq org-startup-indented t)
#+END_SRC

**** org-babel
Eval code blocks without prompting for confirmation.  It's unlikely that this will ever be a security concern.
#+BEGIN_SRC emacs-lisp
(setq org-confirm-babel-evaluate nil)
#+END_SRC

#+BEGIN_SRC emacs-lisp
(org-babel-do-load-languages
 'org-babel-load-languages
 '((sh . t)
   (emacs-lisp . t)
   (ipython . t)))
#+END_SRC

**** org-src
Editing source code blocks should happen in the same window.  The edit session should end after saving the org-src buffer (TODO: submit patch? after-save-hook isn't called by org-edit-src-save so might be better to modify org-edit-src-save itself).
#+BEGIN_SRC emacs-lisp
(setq org-src-window-setup 'current-window)
#+END_SRC

Don't indent the content of src blocks.
#+BEGIN_SRC emacs-lisp
(setq org-edit-src-content-indentation 0)
#+END_SRC

Disable syntax checking in src blocks.
#+BEGIN_SRC emacs-lisp
(add-hook 'org-src-mode-hook
          (lambda ()
            (add-to-list 'flycheck-disabled-checkers 'emacs-lisp-checkdoc)
            (column-enforce-mode 0)))
#+END_SRC

**** Macros
Add an "<el" expansion for emacs-lisp source blocks.
#+BEGIN_SRC emacs-lisp
(add-to-list 'org-structure-template-alist
             '("el" "#+BEGIN_SRC emacs-lisp\n?\n#+END_SRC"))
#+END_SRC

**** Website
When exporting to HTML, highlight the code within src blocks.
#+BEGIN_SRC emacs-lisp
(setq org-src-fontify-natively t)
#+END_SRC

Workaround for a bug with HTML export on emacs-25. http://wenshanren.org/?p=768
#+BEGIN_SRC emacs-lisp
(eval-after-load "/home/nivekuil/docs/website/index.org"
  (defun org-font-lock-ensure ()
    (font-lock-fontify-buffer)))
#+END_SRC

Add more backends to =org-export=.
#+BEGIN_SRC emacs-lisp
(add-to-list 'org-export-backends 'org)
#+END_SRC

The publish function.
#+BEGIN_SRC emacs-lisp
(defun publish-website ()
  (interactive)
  (org-html-export-to-html)
  (call-process-shell-command "~/scripts/publish-website.sh &"))
#+END_SRC

*** Javascript/HTML/CSS
Use js2-mode for editing .js files.
#+BEGIN_SRC emacs-lisp
(add-to-list 'auto-mode-alist '("\\.js$" . js2-mode))
(add-to-list 'auto-mode-alist '("\\.jsx$" . js2-mode))
#+END_SRC

JSON is a subset of YAML, so use yaml-mode to edit json files.
#+BEGIN_SRC emacs-lisp
(add-to-list 'auto-mode-alist '("\\.json$" . yaml-mode))
#+END_SRC

#+BEGIN_SRC emacs-lisp
(setq js-indent-level 2)
#+END_SRC

Use jade for cool features.
#+BEGIN_SRC emacs-lisp
(require 'jade)
(add-hook 'js2-mode-hook #'jade-interaction-mode)
(add-hook 'js2-mode-hook #'tern-mode)
#+END_SRC


*** Rust
#+BEGIN_SRC emacs-lisp
(add-hook 'rust-mode-hook #'racer-mode)
(add-hook 'racer-mode-hook #'eldoc-mode)
(add-hook 'racer-mode-hook #'company-mode)
(eval-after-load 'racer
  (lambda nil (define-key racer-mode-map (kbd "C-c C-d") 'racer-describe)))
(add-hook 'rust-mode-hook
          (lambda nil (local-set-key (kbd "C-c C-c") 'compile-dwim)))
#+END_SRC
*** SQL
#+BEGIN_SRC emacs-lisp
#+END_SRC
*** Term
Set scroll margin in terminal to 0.
#+BEGIN_SRC emacs-lisp
(add-hook 'term-mode-hook (lambda ()
                            (set (make-local-variable 'scroll-margin) 0)))
#+END_SRC

*** Web
#+BEGIN_SRC emacs-lisp
  (add-to-list 'auto-mode-alist '("\\.phtml\\'" . web-mode))
  (add-to-list 'auto-mode-alist '("\\.tpl\\.php\\'" . web-mode))
  (add-to-list 'auto-mode-alist '("\\.[agj]sp\\'" . web-mode))
  (add-to-list 'auto-mode-alist '("\\.as[cp]x\\'" . web-mode))
  (add-to-list 'auto-mode-alist '("\\.erb\\'" . web-mode))
  (add-to-list 'auto-mode-alist '("\\.mustache\\'" . web-mode))
  (add-to-list 'auto-mode-alist '("\\.djhtml\\'" . web-mode))
  (add-to-list 'auto-mode-alist '("\\.html?\\'" . web-mode))
  (add-to-list 'auto-mode-alist '("\\.css?\\'" . web-mode))
#+END_SRC

*** xwidget-webkit
Make the mouse wheel scroll the webkit xwidget, and add the standard keybinding to go back a page.
#+BEGIN_SRC emacs-lisp
(add-hook 'xwidget-webkit-mode-hook
          (lambda ()
            (setq-local mwheel-scroll-up-function
                        (lambda (&optional arg) (xwidget-webkit-scroll-up)))
            (setq-local mwheel-scroll-down-function
                        (lambda (&optional arg) (xwidget-webkit-scroll-down)))
            (local-set-key (kbd "M-<left>") #'xwidget-webkit-back)))

#+END_SRC

Reload automatically, handy for development. Should find a way to do this in background.
#+BEGIN_SRC emacs-lisp
;;(add-hook 'xwidget-webkit-mode-hook
;;          (lambda () (run-with-timer 2 2 'xwidget-webkit-reload)))
#+END_SRC
* Packages
** ace-window
Switch between windows by assigning a number to each one.

** aggressive-indent-mode
Automatically fix indentation as you type.  Nice to have in lisp, but I find it more annoying than useful in other languages.
#+BEGIN_SRC emacs-lisp
(add-hook 'emacs-lisp-mode-hook #'aggressive-indent-mode)
(add-hook 'clojure-mode-hook #'aggressive-indent-mode)
#+END_SRC

** avy
#+BEGIN_SRC emacs-lisp
(setq avy-keys '(?a ?o ?e ?u ?h ?t ?n ?s))
(setq avy-style 'at-full)
(setq avy-background nil)
#+END_SRC

** beacon
Display a beacon when changing windows.
#+BEGIN_SRC emacs-lisp
(beacon-mode 1)
(setq beacon-blink-when-window-scrolls nil)
(add-to-list 'beacon-dont-blink-major-modes 'special-mode)

#+END_SRC

** cider
#+BEGIN_SRC emacs-lisp
(setq cider-default-repl-command "boot")
(setq cider-repl-pop-to-buffer-on-connect nil)
#+END_SRC
** column-enforce-mode
Use column enforce mode to mark text past column 80.
#+BEGIN_SRC emacs-lisp
(add-hook 'c-mode-hook 'column-enforce-mode)
(add-hook 'c++-mode-hook 'column-enforce-mode)
(add-hook 'clojure-mode-hook 'column-enforce-mode)
(add-hook 'js-mode-hook 'column-enforce-mode)
(add-hook 'python-mode-hook 'column-enforce-mode)
#+END_SRC

** command-log-mode
** company-mode
Use company mode for text and code completion.
#+BEGIN_SRC emacs-lisp
(global-company-mode)
(add-to-list 'company-backends 'company-irony)
(add-to-list 'company-backends 'company-irony-c-headers)
(add-to-list 'company-backends 'company-tern)
(setq company-idle-delay 0.15)
#+END_SRC

The dabbrev backends should only look for candidates in buffers with the same major mode.
#+BEGIN_SRC emacs-lisp
(setq company-dabbrev-other-buffers t)
(setq company-dabbrev-code-other-buffers t)
#+END_SRC

Autocomplete should preserve the original case as much as possible.
#+BEGIN_SRC emacs-lisp
(setq company-dabbrev-downcase nil)
(setq company-dabbrev-ignore-case nil)
#+END_SRC

#+BEGIN_SRC emacs-lisp
(setq company-tooltip-align-annotations t)
#+END_SRC

** corral
Best package ever!
#+BEGIN_SRC emacs-lisp
(setq corral-preserve-point t)
(setq corral-syntax-entries '((?# "_")
                              (?* "_")
                              (?- "_")))
#+END_SRC

** deft
#+BEGIN_SRC emacs-lisp
(setq deft-directory "/home/nivekuil/docs/deft/")
(setq deft-extension "org")
(setq deft-default-extension "org")
(setq deft-text-mode 'org-mode)
(setq deft-auto-save-interval 0)
(setq deft-width-offset 3)
#+END_SRC

Use hl-line-mode in the deft buffer.
#+BEGIN_SRC emacs-lisp
(add-hook 'deft-mode-hook (lambda () (hl-line-mode 1)))
#+END_SRC

** elpy
#+BEGIN_SRC emacs-lisp
(elpy-enable)
(setq elpy-rpc-backend "jedi")
#+END_SRC

Highlighting indentation levels makes Python ugly, and isn't very useful in practice.
#+BEGIN_SRC emacs-lisp
(setq elpy-modules (delete 'elpy-module-highlight-indentation elpy-modules))
#+END_SRC
** flycheck
Use flycheck for syntax checking.
#+BEGIN_SRC emacs-lisp
(add-hook 'after-init-hook #'global-flycheck-mode)
(setq flycheck-global-modes '(not emacs-lisp-mode))
(add-hook 'flycheck-mode-hook #'flycheck-irony-setup)
(add-hook 'flycheck-mode-hook #'flycheck-rust-setup)
(setq flycheck-display-errors-delay 0.4)


#+END_SRC
*** flycheck-pos-tip
#+BEGIN_SRC emacs-lisp
(with-eval-after-load 'flycheck
  (flycheck-pos-tip-mode))
(setq flycheck-pos-tip-timeout 30)
#+END_SRC
** helm
The following must be set before helm is loaded when tethered to my phone due to T-Mobile's DNS hijacking, or it will hang emacs.
#+BEGIN_SRC emacs-lisp
;;(setq tramp-ssh-controlmaster-options "-o ControlMaster=auto -o ControlPath='tramp.%%C' -o ControlPersist=no")
#+END_SRC

#+BEGIN_SRC emacs-lisp
(helm-mode t)
#+END_SRC
Swap <tab> and C-z in helm buffers
#+BEGIN_SRC emacs-lisp
(define-key helm-map (kbd "TAB") 'helm-execute-persistent-action)
(define-key helm-map (kbd "C-z") 'helm-select-action)
#+END_SRC

Make helm buffers appear on the bottom half of the window.
#+BEGIN_SRC emacs-lisp
(setq helm-split-window-in-side-p t)
(setq helm-split-window-default-side 'below)
#+END_SRC

Use fuzzy matching with helm-apropos
#+BEGIN_SRC emacs-lisp
(setq helm-apropos-fuzzy-match t)
#+END_SRC

Show helm input within the helm window.
#+BEGIN_SRC emacs-lisp
(setq helm-echo-input-in-header-line t)
#+END_SRC

*** helm-web
#+BEGIN_SRC emacs-lisp
(setq helm-net-prefer-curl t)
#+END_SRC

*** helm-projectile
#+BEGIN_SRC emacs-lisp
(helm-projectile-on)
#+END_SRC
** helm-ag
#+BEGIN_SRC emacs-lisp
(setq helm-ag-fuzzy-match t)
#+END_SRC

** hungry-delete-mode
Delete all whitespace instead of doing it one character at a time.
#+BEGIN_SRC emacs-lisp
(hungry-delete-mode 1)
(add-hook 'prog-mode-hook (lambda nil (hungry-delete-mode 1)))
#+END_SRC

** magit
#+BEGIN_SRC emacs-lisp
(setq magit-last-seen-setup-instructions "1.4.0")
#+END_SRC

** mu4e
mu4e is not part of elpa, so we have to require it manually instead of letting package-initialize handle it.
#+BEGIN_SRC emacs-lisp
(add-to-list 'load-path "/usr/share/emacs/site-lisp/mu4e/")
(require 'mu4e)
(setq mu4e-headers-date-format "%b %d")
(setq mu4e-headers-time-format "%H:%M")
(setq mu4e-headers-fields '((:human-date . 7) (:from . 15) (:subject)))


#+END_SRC
Command run to sync mailboxes.  mbsync seems to have no timeout handling built in (and it gets stuck a lot), so we use the timeout utility to run it.
#+BEGIN_SRC emacs-lisp
  (setq mu4e-get-mail-command "timeout -s TERM 60 mbsync -a")
#+END_SRC

Update mailboxes every 5 minutes.
#+BEGIN_SRC emacs-lisp
(setq mu4e-update-interval 300)
(setq mu4e-hide-index-messages t)
#+END_SRC

Use zoho as default mailbox.
#+BEGIN_SRC emacs-lisp
(setq mu4e-maildir       "~/.mail"              ;; top-level Maildir
      mu4e-sent-folder   "/zoho/Sent"
      mu4e-drafts-folder "/zoho/Drafts"
      mu4e-trash-folder  "/zoho/Trash")

#+END_SRC

Enabling this will make mbsync not break with a maildir error about UIDs.  Offlineimap prefers this to be nil.
#+BEGIN_SRC emacs-lisp
(setq mu4e-change-filenames-when-moving t)
#+END_SRC

Show images in emails.
#+BEGIN_SRC emacs-lisp
(setq mu4e-view-show-images t)
#+END_SRC

Gmail and offlineimap leads to duplicate emails showing up in search filters since that's the way labels/virtual folders in Gmail are represented, so skip them.
#+BEGIN_SRC emacs-lisp
(setq mu4e-headers-skip-duplicates t)
#+END_SRC

Use =mu4e-shr2text= found in the =mu4e-contrib= package to display rich text messages.
#+BEGIN_SRC emacs-lisp
(require 'mu4e-contrib)
(setq mu4e-html2text-command 'mu4e-shr2text)
#+END_SRC

Settings for sending mail using TLS encryption.  Use ~/.authinfo (or ~/.authinfo.gpg) for credentials.
#+BEGIN_SRC emacs-lisp
  (require 'smtpmail)
  (setq user-mail-address (concat "kevin" "@nivekuil.com")
        message-send-mail-function 'smtpmail-send-it
        smtpmail-smtp-server "smtp.zoho.com"
        smtpmail-stream-type 'starttls
        smtpmail-smtp-service 587)      ;TLS port
  (setq mu4e-maildir-shortcuts
    '(("/zoho/Inbox" . ?j)))
  (add-hook 'message-send-hook 'mml-secure-message-sign-pgpmime)
#+END_SRC

#+BEGIN_SRC emacs-lisp
(defun my-mu4e-action-view-with-xwidget (msg)
  "View the body of the message inside xwidget-webkit."
  (unless (fboundp 'xwidget-webkit-browse-url)
    (mu4e-error "No xwidget support available"))
  (let* ((html (mu4e-message-field msg :body-html))
          (txt (mu4e-message-field msg :body-txt))
          (tmpfile (format "%s%x.html" temporary-file-directory (random t))))
    (unless (or html txt)
      (mu4e-error "No body part for this message"))
    (with-temp-buffer
      ;; simplistic -- but note that it's only an example...
      (insert (or html (concat "<pre>" txt "</pre>")))
      (write-file tmpfile)
      (xwidget-webkit-browse-url (concat "file://" tmpfile) t))))

(add-to-list 'mu4e-view-actions
  '("xViewXWidget" . my-mu4e-action-view-with-xwidget) t)
#+END_SRC

Start mu4e in the background.
#+BEGIN_SRC emacs-lisp
;;(add-hook 'after-init-hook 'mu4e)
#+END_SRC

** mu4e-alert
Use libnotify to send notifications about new emails.
#+BEGIN_SRC emacs-lisp
(mu4e-alert-set-default-style 'libnotify)
(mu4e-alert-enable-notifications)
#+END_SRC

** polymode
Override polymode key bindings.
#+BEGIN_SRC emacs-lisp
(eval-after-load 'polymode
  (lambda nil
    (define-key polymode-mode-map (kbd "M-n") 'forward-paragraph)
    (define-key polymode-mode-map (kbd "M-p") 'backward-paragraph)))
#+END_SRC
** projectile
#+BEGIN_SRC emacs-lisp
(projectile-global-mode t)
#+END_SRC

Disable the projectile mode line, if only because it slows TRAMP to a crawl.
#+BEGIN_SRC emacs-lisp
(setq projectile-mode-line nil)
#+END_SRC

** puml-mode
#+BEGIN_SRC emacs-lisp
(setq puml-plantuml-jar-path (concat (expand-file-name user-emacs-directory) "util/plantuml.jar"))
#+END_SRC

** spaceline
#+BEGIN_SRC emacs-lisp
(require 'spaceline-config)
(spaceline-emacs-theme)
(spaceline-toggle-minor-modes-off)
(spaceline-toggle-buffer-encoding-abbrev-off)
(setq spaceline-highlight-face-func 'spaceline-highlight-face-modified)
#+END_SRC
** swiper
Backspace should not end swiper.
#+BEGIN_SRC emacs-lisp
(setq ivy-on-del-error-function nil)
#+END_SRC

** symon
Mini system monitor that pops up in the minibuffer after a period of idleness.
#+BEGIN_SRC emacs-lisp
(setq symon-delay 30)
(setq symon-sparkline-width 1)
(setq symon-refresh-rate 2)
(symon-mode 1)
#+END_SRC

** rainbow-delimiters
Highlight parens levels in lisps.
#+BEGIN_SRC emacs-lisp
(add-hook 'emacs-lisp-mode-hook #'rainbow-delimiters-mode)
(add-hook 'clojure-mode-hook #'rainbow-delimiters-mode)
#+END_SRC

** whole-line-or-region
Use whole line or region so C-w and M-w without an active mark kills the line.
#+BEGIN_SRC emacs-lisp
(whole-line-or-region-mode t)
#+END_SRC

** ws-butler
Automatically and non-disruptively clean up whitespace on save.
#+BEGIN_SRC emacs-lisp
(ws-butler-global-mode t)
#+END_SRC

** yasnippet
#+BEGIN_SRC emacs-lisp
(setq yas-snippet-dirs '("~/.emacs.d/snippets"))
(yas-global-mode t) ;; Activate global mode before defining keys
#+END_SRC

Yasnippet blocks shell tab completion, so disable it in comint and term modes.
#+BEGIN_SRC emacs-lisp
(add-hook 'comint-mode-hook (lambda () (yas-minor-mode -1)))
(add-hook 'term-mode-hook (lambda () (yas-minor-mode -1)))
#+END_SRC
